### ISSUE TITLE
Yarn v2 Support

### ISSUE THREAD

**Issue by KyleBastien** [zumwald/better-vsts-npm-auth#38]
Thank you so much for this awesome tool!

It would be great if this also supported Yarn v2!

Currently this works very well with Yarn v1, because Yarn v1 will read from a `.npmrc` file.

But, this doesn't work with Yarn v2, because Yarn v2 does not support the `.npmrc` file, it only supports the `.yarnrc.yml` file.

I think this could be implemented in `better-vsts-npm-auth` by doing the following:

- Check to see if a `.yarnrc.yml` file exists in the current directory (this would be an indication that the user is using Yarn v2)
- If the user is using Yarn v2, write to `~/.yarnrc.yaml` instead of `.npmrc`
- Write the `~/.yarnrc.yaml` file with something like:

```yaml
npmRegistries:
  //registry.name.com:
    npmAuthIdent: 'base64Encoded(vstsOrgName:vstsPersonalAccessToken)'
```

I'd be happy to contribute this, if this is something desired, with some pointers around the code, if possible!

Thank you!
